version: '3'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_billetera.sql:/docker-entrypoint-initdb.d/db_billetera.sql
    environment:
      POSTGRES_DB: db_billetera
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  web:
    build: .
    command: sh /app/startup.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/db_billetera

volumes:
  postgres_data:
